---
name: VanillaInventory
version: 1.1.2
main: korado531m7\VanillaInventory\Main
api: 3.19.0
mcpe-protocol: [431, 440, 448, 465]
deescription: Enable to use enchantment and anvil GUI
author: korado531m7
...
